call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\cdk\cdk1_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\cdk\cdk1.1_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\cdk\cdk1.1_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\cdk\cdk1.2_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\cmusphinx\cmusphinx3.6_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\cmusphinx\cmusphinx3.7_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\controltier\controltier3_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\controltier\controltier3.1_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\controltier\controltier3.1_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\controltier\controltier3.2_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\drjava\drjava2008_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\drjava\drjava2009_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\drjava\drjava2009_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\drjava\drjava2010_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\eclemma\eclemma2_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\eclemma\eclemma2.1_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\genoviz\genoviz5.4_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\genoviz\genoviz6_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\genoviz\genoviz6_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\genoviz\genoviz6.1_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\genoviz\genoviz6.1_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\genoviz\genoviz6.2_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\genoviz\genoviz6.2_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\genoviz\genoviz6.3_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\htmlunit\htmlunit2008_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\htmlunit\htmlunit2009_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\htmlunit\htmlunit2009_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\htmlunit\htmlunit2010_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jikesrvm\jikesrvm2_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jikesrvm\jikesrvm3_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jikesrvm\jikesrvm3_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jikesrvm\jikesrvm3.1_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jitterbit\jitterbit1.1_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jitterbit\jitterbit1.2_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol2_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol3_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol3_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol4_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol4_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol5_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol5_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol6_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol6_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol7_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol7_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol8_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol8_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol9_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol9_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmol\jmol10_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmri\jmri2_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmri\jmri2.2_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmri\jmri2.2_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmri\jmri2.4_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmri\jmri2.4_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jmri\jmri2.6_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jppf\jppf4_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jppf\jppf4.1_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jppf\jppf4.1_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jppf\jppf4.2_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jppf\jppf4.2_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jppf\jppf5_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jppf\jppf5_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jppf\jppf5.1_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jump\jump1.5_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jump\jump1.6_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jump\jump1.6_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jump\jump1.7_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jump\jump1.7_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jump\jump1.8_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jump\jump1.8_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\jump\jump1.9_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\omegat\omegat3.1_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\omegat\omegat3.5_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\omegat\omegat3.5_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\omegat\omegat3.6_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\runawfe\runawfe3.5_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\runawfe\runawfe3.6_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\runawfe\runawfe3.6_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\runawfe\runawfe4.1_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\runawfe\runawfe4.1_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\runawfe\runawfe4.2_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\unicore\unicore1.2_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\unicore\unicore1.3_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\unicore\unicore1.3_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\unicore\unicore1.4_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\unicore\unicore1.4_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\unicore\unicore1.5_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\unicore\unicore1.5_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\unicore\unicore1.6_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\xaware\xaware5_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\xaware\xaware5.1_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\xaware\xaware5.1_ClassLevelMetrics.csv   .\cross-version-instance-overlap\ESEM2016-master\ClassLevel_processed\xaware\xaware6_ClassLevelMetrics.csv --result-path result\KNN4ns\ELFF_class_result\ --drops "Class Package NumberOfDefects" --sloc nloc --ids "Class Package" --label Defective --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ant\ant_1.3.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ant\ant_1.4.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ant\ant_1.4.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ant\ant_1.5.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ant\ant_1.5.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ant\ant_1.6.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ant\ant_1.6.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ant\ant_1.7.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\camel\camel_1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\camel\camel_1.2.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\camel\camel_1.2.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\camel\camel_1.4.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\camel\camel_1.4.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\camel\camel_1.6.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\forrest\forrest_0.6.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\forrest\forrest_0.7.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\forrest\forrest_0.7.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\forrest\forrest_0.8.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ivy\ivy_1.1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ivy\ivy_1.4.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ivy\ivy_1.4.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\ivy\ivy_2.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\jEdit\jEdit_3.2.1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\jEdit\jEdit_4.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\jEdit\jEdit_4.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\jEdit\jEdit_4.1.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\jEdit\jEdit_4.1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\jEdit\jEdit_4.2.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\jEdit\jEdit_4.2.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\jEdit\jEdit_4.3.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\log4j\log4j_1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\log4j\log4j_1.1.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\log4j\log4j_1.1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\log4j\log4j_1.2.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\lucene\lucene_2.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\lucene\lucene_2.2.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\lucene\lucene_2.2.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\lucene\lucene_2.4.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\pBeans\pBeans_1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\pBeans\pBeans_2.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\poi\poi_1.5.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\poi\poi_2.0RC1.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\poi\poi_2.0RC1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\poi\poi_2.5.1.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\poi\poi_2.5.1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\poi\poi_3.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\synapse\synapse_1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\synapse\synapse_1.1.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\synapse\synapse_1.1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\synapse\synapse_1.2.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\velocity\velocity_1.4.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\velocity\velocity_1.5.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\velocity\velocity_1.5.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\velocity\velocity_1.6.1.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xalan\xalan_2.4.0.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xalan\xalan_2.5.0.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xalan\xalan_2.5.0.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xalan\xalan_2.6.0.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xalan\xalan_2.6.0.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xalan\xalan_2.7.0.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xerces\xerces_1.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xerces\xerces_1.2.0.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xerces\xerces_1.2.0.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xerces\xerces_1.3.0.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xerces\xerces_1.3.0.csv  .\cross-version-instance-overlap\JURECZKO\data_preprocessed_selected\xerces\xerces_1.4.4.csv --result-path result\KNN4ns\JURECZKO_result\ --label defective --drops "Project Class bugs" --sloc loc --ids "Project Class" --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\cdk\metricsFlagsDefects_cdk1.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\cdk\metricsFlagsDefects_cdk1.1.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\cdk\metricsFlagsDefects_cdk1.1.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\cdk\metricsFlagsDefects_cdk1.2.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\cmusphinx\metricsFlagsDefects_cmusphinx3.6.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\cmusphinx\metricsFlagsDefects_cmusphinx3.7.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\controltier\metricsFlagsDefects_controltier3.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\controltier\metricsFlagsDefects_controltier3.1.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\controltier\metricsFlagsDefects_controltier3.1.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\controltier\metricsFlagsDefects_controltier3.2.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\drjava\metricsFlagsDefects_drjava2008.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\drjava\metricsFlagsDefects_drjava2009.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\drjava\metricsFlagsDefects_drjava2009.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\drjava\metricsFlagsDefects_drjava2010.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\eclemma\metricsFlagsDefects_eclemma2.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\eclemma\metricsFlagsDefects_eclemma2.1.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\genoviz\metricsFlagsDefects_genoviz5.4.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\genoviz\metricsFlagsDefects_genoviz6.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\genoviz\metricsFlagsDefects_genoviz6.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\genoviz\metricsFlagsDefects_genoviz6.1.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\genoviz\metricsFlagsDefects_genoviz6.1.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\genoviz\metricsFlagsDefects_genoviz6.2.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\genoviz\metricsFlagsDefects_genoviz6.2.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\genoviz\metricsFlagsDefects_genoviz6.3.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\htmlunit\metricsFlagsDefects_htmlunit2008.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\htmlunit\metricsFlagsDefects_htmlunit2009.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\htmlunit\metricsFlagsDefects_htmlunit2009.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\htmlunit\metricsFlagsDefects_htmlunit2010.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jikesrvm\metricsFlagsDefects_jikesrvm2.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jikesrvm\metricsFlagsDefects_jikesrvm3.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jikesrvm\metricsFlagsDefects_jikesrvm3.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jikesrvm\metricsFlagsDefects_jikesrvm3.1.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jitterbit\metricsFlagsDefects_jitterbit1.1.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jitterbit\metricsFlagsDefects_jitterbit1.2.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol2.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol3.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol3.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol4.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol4.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol5.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol5.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol6.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol6.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol7.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol7.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol8.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol8.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol9.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol9.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmol\metricsFlagsDefects_jmol10.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmri\metricsFlagsDefects_jmri2.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmri\metricsFlagsDefects_jmri2.2.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmri\metricsFlagsDefects_jmri2.2.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmri\metricsFlagsDefects_jmri2.4.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmri\metricsFlagsDefects_jmri2.4.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jmri\metricsFlagsDefects_jmri2.6.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jppf\metricsFlagsDefects_jppf4.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jppf\metricsFlagsDefects_jppf4.1.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jppf\metricsFlagsDefects_jppf4.1.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jppf\metricsFlagsDefects_jppf4.2.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jppf\metricsFlagsDefects_jppf4.2.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jppf\metricsFlagsDefects_jppf5.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jppf\metricsFlagsDefects_jppf5.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jppf\metricsFlagsDefects_jppf5.1.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jump\metricsFlagsDefects_jump1.5.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jump\metricsFlagsDefects_jump1.6.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jump\metricsFlagsDefects_jump1.6.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jump\metricsFlagsDefects_jump1.7.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jump\metricsFlagsDefects_jump1.7.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jump\metricsFlagsDefects_jump1.8.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jump\metricsFlagsDefects_jump1.8.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\jump\metricsFlagsDefects_jump1.9.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\omegat\metricsFlagsDefects_omegat3.1.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\omegat\metricsFlagsDefects_omegat3.5.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\omegat\metricsFlagsDefects_omegat3.5.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\omegat\metricsFlagsDefects_omegat3.6.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\runawfe\metricsFlagsDefects_runawfe3.5.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\runawfe\metricsFlagsDefects_runawfe3.6.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\runawfe\metricsFlagsDefects_runawfe3.6.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\runawfe\metricsFlagsDefects_runawfe4.1.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\runawfe\metricsFlagsDefects_runawfe4.1.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\runawfe\metricsFlagsDefects_runawfe4.2.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\unicore\metricsFlagsDefects_unicore1.2.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\unicore\metricsFlagsDefects_unicore1.3.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\unicore\metricsFlagsDefects_unicore1.3.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\unicore\metricsFlagsDefects_unicore1.4.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\unicore\metricsFlagsDefects_unicore1.4.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\unicore\metricsFlagsDefects_unicore1.5.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\unicore\metricsFlagsDefects_unicore1.5.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\unicore\metricsFlagsDefects_unicore1.6.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\xaware\metricsFlagsDefects_xaware5.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\xaware\metricsFlagsDefects_xaware5.1.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns
call .\venv\Scripts\python.exe .\main.py .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\xaware\metricsFlagsDefects_xaware5.1.csv   .\cross-version-instance-overlap\ESEM2016-master\MethodLevel_processed\xaware\metricsFlagsDefects_xaware6.csv --result-path result\KNN4ns\ELFF_Method_result\ --drops "Class Package Method SEQUENCE FLAG" --sloc NLOC --ids "Class Package Method" --label DEFECTIVE --model KNN4ns