res <- summaryPerformance2(root_path='./result/LR/ELFF_class_result/',threshold = -1, mode='')
write.csv(res,file='./performance/LR_ELFF_class_result_-1.csv',row.names = FALSE)
res <- summaryPerformance2(root_path='./result/LR/ELFF_class_result/',threshold = 0.2, mode='SNM')
write.csv(res,file='./performance/LR_ELFF_class_result_0.2.csv',row.names = FALSE)
res <- summaryPerformance2(root_path='./result/LR/ELFF_class_result/',threshold = 20, mode='SSC')
write.csv(res,file='./performance/LR_ELFF_class_result_20.csv',row.names = FALSE)

res <- summaryPerformance2(root_path='./result/LR/ELFF_Method_result/',threshold = -1, mode='')
write.csv(res,file='./performance/LR_ELFF_Method_result_-1.csv',row.names = FALSE)
res <- summaryPerformance2(root_path='./result/LR/ELFF_Method_result/',threshold = 0.2, mode='SNM')
write.csv(res,file='./performance/LR_ELFF_Method_result_0.2.csv',row.names = FALSE)
res <- summaryPerformance2(root_path='./result/LR/ELFF_Method_result/',threshold = 20, mode='SSC')
write.csv(res,file='./performance/LR_ELFF_Method_result_20.csv',row.names = FALSE)

res <- summaryPerformance2(root_path='./result/LR/ELFF_Method_result/',threshold = -1, mode='')
write.csv(res,file='./performance/LR_ELFF_Method_result_-1.csv',row.names = FALSE)
res <- summaryPerformance2(root_path='./result/LR/ELFF_Method_result/',threshold = 0.2, mode='SNM')
write.csv(res,file='./performance/LR_ELFF_Method_result_0.2.csv',row.names = FALSE)
res <- summaryPerformance2(root_path='./result/LR/ELFF_Method_result/',threshold = 20, mode='SSC')
write.csv(res,file='./performance/LR_ELFF_Method_result_20.csv',row.names = FALSE)